### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by rodrigoguarch** [ldtteam/Domum-Ornamentum#169]
When I want to see the items in the page 20 of JEI an item from domum crashes my game.
There's the Crash Report: https://mclo.gs/xaT4rlh

**Comment by MotionlessTrain** [comment]
Don't use optifine. It doesn't work well together with forge.

Instead of optifine, we recommend installing
- Rubidium (for the graphics improvements)
  <https://www.curseforge.com/minecraft/mc-mods/rubidium>, and
- Oculus (for the shaders loading. Note that Oculus requires Rubidium!)
  <https://www.curseforge.com/minecraft/mc-mods/oculus>
